server:
  port: 8083

application:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/easygig-notifications
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_CLIENT_MAIL}
    password: ${GOOGLE_PASSWORD_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Configurazione Kafka Consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.spring.*"
        spring.json.use.type.headers: "true"
        spring.json.type.mapping: "org.spring.bookingservice.dto.BookingCanceledEvent:org.spring.notificationservice.dto.BookingCanceledEvent,org.spring.bookingservice.dto.BookingAcceptedEvent:org.spring.notificationservice.dto.BookingAcceptedEvent,org.spring.bookingservice.dto.BookingRejectedEvent:org.spring.notificationservice.dto.BookingRejectedEvent,org.spring.bookingservice.dto.BookingRequestCreatedEvent:org.spring.notificationservice.dto.BookingRequestCreatedEvent,org.spring.bookingservice.dto.BookingExpiredEvent:org.spring.notificationservice.dto.BookingExpiredEvent"

logging:
  file:
    name: logs/notification-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka