server:
  port: 8083

application:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/easygig-profiles
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_CLIENT_MAIL}
    password: ${GOOGLE_PASSWORD_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  # Configurazione Kafka Consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka