server:
  port: 8081

spring:
  application:
    name: profile-service
  datasource:
      url: jdbc:postgresql://localhost:5432/easygig-profiles
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

application:
  frontend:
    url: http://localhost:3000/register
  invitation:
    expiry-days: 7
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

spring.kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: org.spring.profileservice.controller
