server:
  port: 8761 #Porta Standard Eureka

spring:
  application:
    name: discovery-server

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false #il server non deve registrarsi a se stesso
    fetch-registry: false #Il server non deve scaricare l'elenco da se stesso